# Generated by Django 3.2.6 on 2021-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracaoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracaoes',
            name='data_evento',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
