# Generated by Django 3.2.6 on 2021-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracaoes', '0002_atracaoes_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracaoes',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
