# Generated by Django 3.2.6 on 2021-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacaoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoes',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
