# Generated by Django 3.2.6 on 2021-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.TextField()),
                ('numero', models.IntegerField()),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=150)),
                ('ponto_referencia', models.CharField(max_length=150)),
                ('longitude', models.IntegerField(null=True)),
                ('latitude', models.IntegerField(null=True)),
            ],
        ),
    ]
