# Generated by Django 3.2.6 on 2021-08-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
