# Generated by Django 3.2.6 on 2021-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracaoes', '0002_atracaoes_data_evento'),
        ('core', '0002_alter_pontosturisticos_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='Atracaoes',
            field=models.ManyToManyField(to='atracaoes.Atracaoes'),
        ),
    ]
