# Generated by Django 3.2.6 on 2021-08-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontosturisticos_atracaoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='Comentario',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
