# Generated by Django 3.2.6 on 2021-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacaoes', '0001_initial'),
        ('core', '0004_pontosturisticos_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='avaliacaoes',
            field=models.ManyToManyField(to='avaliacaoes.Avaliacaoes'),
        ),
    ]
