# Generated by Django 3.2.6 on 2021-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turistico'),
        ),
    ]
