# Generated by Django 3.2.6 on 2021-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pontosturisticos_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='teste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
