# Generated by Django 3.2.6 on 2021-08-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pontosturisticos_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturisticos',
            name='teste',
        ),
    ]
