# Generated by Django 3.2.6 on 2021-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pontosturisticos_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
    ]
